version: "3.9"
services:
  db:
    build: ./db
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes: 
      - type: bind
        source: ./api/weblog
        target: /api/weblog
      - type: bind
        source: ./api/tests
        target: /api/tests
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      SECRET_KEY: $SECRET_KEY
      WATCHFILES_FORCE_POLLING: true
